services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:your-app-key-here
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
      - MAIL_MAILER=log
    volumes:
      - ./storage:/var/www/storage
      - ./database:/var/www/database
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      - redis
    networks:
      - laravel

  # Development services
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:your-app-key-here
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      - VITE_DEV_SERVER_URL=http://localhost:5173
      - VITE_HMR_HOST=localhost
    volumes:
      - .:/var/www
      - /var/www/node_modules
      - /var/www/vendor
    working_dir: /var/www
    command: composer dev:docker
    profiles:
      - dev
    networks:
      - laravel

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    profiles:
      - mysql
    networks:
      - laravel

volumes:
  redis_data:
  mysql_data:

networks:
  laravel:
    driver: bridge